### ISSUE TITLE
项目在linux下构建无效

### ISSUE THREAD

**Issue by SquareCM2** [A4-Tacks/blockly_for_mindustry_logic_bang_lang#2]
在ubuntu 22.04 LTS版本使用`yarn build`进行构建时报错
`00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'build'
`
这是为什么？如果项目本身没有问题则可以关闭此issue

**Comment by A4-Tacks** [comment]
你是否在shell中键入`yarn build`得到此错误？
如果是，确保你安装了node.js npm yarn
如果不是，可以将环境及完整日志等一并附上

我的开发环境就是Linux

**Comment by A4-Tacks** [comment]
正常情况下，它将会产生如下输出：
```bash
    $ yarn build
yarn run v1.22.21
$ webpack --mode production
asset bundle.js 720 KiB [emitted] [minimized] [big] (name: main) 1 related asset
asset index.html 681 bytes [emitted]
orphan modules 76 KiB [orphan] 5 modules
runtime modules 919 bytes 5 modules
modules by path ./node_modules/ 1.04 MiB
  modules by path ./node_modules/blockly/ 1.03 MiB
    ./node_modules/blockly/index.js 622 bytes [built] [code generated]
    + 9 modules
  modules by path ./node_modules/style-loader/dist/runtime/*.js 5.84 KiB
    ./node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js 2.42 KiB [built] [code generated]
    + 5 modules
  modules by path ./node_modules/css-loader/dist/runtime/*.js 2.31 KiB
    ./node_modules/css-loader/dist/runtime/noSourceMaps.js 64 bytes [built] [code generated]
    ./node_modules/css-loader/dist/runtime/api.js 2.25 KiB [built] [code generated]
modules by path ./src/ 79.4 KiB
  ./src/index.js + 5 modules 78.4 KiB [built] [code generated]
  ./node_modules/css-loader/dist/cjs.js!./src/index.css 1 KiB [built] [code generated]

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  bundle.js (720 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 K
iB). This can impact web performance.
Entrypoints:
  main (720 KiB)
      bundle.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application
.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack 5.89.0 compiled with 3 warnings in 14173 ms
Done in 17.07s.
```

**Comment by SquareCM2** [comment]
> 你是否在shell中键入`yarn build`得到此错误？ 如果是，确保你安装了node.js npm yarn 如果不是，可以将环境及完整日志等一并附上
> 
> 我的开发环境就是Linux

在shell中使用并得到此错误
已确认安装了node.js npm yarn

**Comment by A4-Tacks** [comment]
使用`yarn build`实则是调用了依赖项中的`webpack`
来源于[此处](https://github.com/A4-Tacks/blockly_for_mindustry_logic_bang_lang/blob/e5222e3426cd04dc3fa841e847b9215b98970e29/package.json#L10)的配置，你或许可以尝试手动运行它

**Comment by SquareCM2** [comment]
> 使用`yarn build`实则是调用了依赖项中的`webpack` 来源于[此处](https://github.com/A4-Tacks/blockly_for_mindustry_logic_bang_lang/blob/e5222e3426cd04dc3fa841e847b9215b98970e29/package.json#L10)的配置，你或许可以尝试手动运行它

具体如何手动运行？
或者如何使得`yarn build`能够被成功使用？

**Comment by A4-Tacks** [comment]
手动运行参考上述给出的链接，在那里，配置了如何调用依赖项目中的webpack并传参
手动调用应该类似以下操作
```bash
./node_modules/webpack/bin/webpack.js --mode production
```
我认为你应该可以看懂

**Comment by SquareCM2** [comment]
> 使用`yarn build`实则是调用了依赖项中的`webpack` 来源于[此处](https://github.com/A4-Tacks/blockly_for_mindustry_logic_bang_lang/blob/e5222e3426cd04dc3fa841e847b9215b98970e29/package.json#L10)的配置，你或许可以尝试手动运行它

手动运行出现以下信息并构建失败
```
$ webpack --mode production
/usr/share/nodejs/webpack/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

Error: Cannot find module 'html-webpack-plugin'
Require stack:
- /home/squarecm2/blockly_for_mindustry_logic_bang_lang/webpack.config.js
- /usr/share/nodejs/webpack/node_modules/webpack-cli/bin/utils/convert-argv.js
- /usr/share/nodejs/webpack/node_modules/webpack-cli/bin/cli.js
- /usr/share/nodejs/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (/usr/share/nodejs/webpack/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/squarecm2/blockly_for_mindustry_logic_bang_lang/webpack.config.js:2:27)
    at Module._compile (/usr/share/nodejs/webpack/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (/usr/share/nodejs/webpack/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/usr/share/nodejs/webpack/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/usr/share/nodejs/webpack/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /usr/share/nodejs/webpack/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/usr/share/nodejs/webpack/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at /usr/share/nodejs/webpack/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/usr/share/nodejs/yargs/build/index.cjs:2281:13)
    at /usr/share/nodejs/webpack/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/usr/share/nodejs/webpack/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/share/nodejs/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/squarecm2/blockly_for_mindustry_logic_bang_lang/webpack.config.js',
    '/usr/share/nodejs/webpack/node_modules/webpack-cli/bin/utils/convert-argv.js',
    '/usr/share/nodejs/webpack/node_modules/webpack-cli/bin/cli.js',
    '/usr/share/nodejs/webpack/bin/webpack.js'
  ]
}
```

**Comment by A4-Tacks** [comment]
或许你少安装了什么，报错很明显的指出缺少了什么

**Comment by A4-Tacks** [comment]
看起来你的webpack是通过包管理器安装的？
要不要尝试删除包管理器安装的webpack再尝试构建呢？因为全局的webpack似乎会对局部的进行覆盖

**Comment by SquareCM2** [comment]
```
$ webpack --mode production
找不到命令 “webpack”，但可以通过以下软件包安装它：
sudo apt install webpack
$ ./node_modules/webpack/bin/webpack.js --mode production
bash: ./node_modules/webpack/bin/webpack.js: 没有那个文件或目录
```

**Comment by A4-Tacks** [comment]
> ```
> $ webpack --mode production
> 找不到命令 “webpack”，但可以通过以下软件包安装它：
> sudo apt install webpack
> $ ./node_modules/webpack/bin/webpack.js --mode production
> bash: ./node_modules/webpack/bin/webpack.js: 没有那个文件或目录
> ```

你是否将依赖全部下载完毕，比如运行`yarn install`?

**Comment by SquareCM2** [comment]
> > ```
> > $ webpack --mode production
> > 找不到命令 “webpack”，但可以通过以下软件包安装它：
> > sudo apt install webpack
> > $ ./node_modules/webpack/bin/webpack.js --mode production
> > bash: ./node_modules/webpack/bin/webpack.js: 没有那个文件或目录
> > ```
> 
> 你是否将依赖全部下载完毕，比如运行`yarn install`?

`00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'`

**Comment by A4-Tacks** [comment]
> `00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'`

我怀疑你的yarn是有问题的，如果`yarn --version`没有正确的输出yarn版本号的话，请使用正常yarn
如果正确的输出了yarn版本号，请附上它到底是什么版本，尝试将其全部升级到最新稳定版

**Comment by SquareCM2** [comment]
```
$ yarn --version
0.32+git
$ sudo apt install yarn
[sudo] squarecm2 的密码： 
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
注意，选中 'cmdtest' 而非 'yarn'
cmdtest 已经是最新版 (0.32.14.gcdfe14e-2)。
下列软件包是自动安装的并且现在不需要了：
  libjs-terser libjs-util node-acorn node-ajv node-ajv-keywords node-anymatch
  node-array-union node-array-uniq node-asn1.js node-assert node-async-each
  node-base64-js node-big.js node-binary-extensions node-bn.js node-braces
  node-brorand node-browserify-aes node-browserify-cipher node-browserify-des
  node-browserify-rsa node-browserify-sign node-browserify-zlib
  node-browserslist node-buffer node-buffer-xor node-builtin-status-codes
  node-camelcase node-caniuse-lite node-chokidar node-cipher-base node-cliui
  node-commondir node-console-browserify node-constants-browserify
  node-create-ecdh node-create-hash node-create-hmac node-crypto-browserify
  node-debbundle-es-to-primitive node-decamelize node-deep-equal
  node-define-properties node-del node-des.js node-detect-file
  node-domain-browser node-electron-to-chromium node-elliptic node-emojis-list
  node-enhanced-resolve node-errno node-es-abstract node-esrecurse
  node-estraverse node-evp-bytestokey node-expand-tilde node-fast-deep-equal
  node-fill-range node-find-cache-dir node-find-up node-findup-sync
  node-fs-exists-sync node-get-caller-file node-glob-parent
  node-global-modules node-global-prefix node-globby node-hash-base
  node-hash.js node-hmac-drbg node-https-browserify node-ieee754 node-ignore
  node-interpret node-is-binary-path node-is-extglob node-is-glob
  node-is-number node-is-path-cwd node-is-path-inside
  node-json-schema-traverse node-json-stable-stringify node-json5 node-jsonify
  node-libs-browser node-loader-runner node-loader-utils node-locate-path
  node-make-dir node-md5.js node-memory-fs node-micromatch
  node-minimalistic-crypto-utils node-neo-async node-normalize-path
  node-object-inspect node-os-browserify node-p-limit node-p-locate node-pako
  node-parse-asn1 node-path-browserify node-path-dirname node-path-exists
  node-path-is-inside node-path-type node-pbkdf2 node-picocolors node-pify
  node-pkg-dir node-process node-prr node-public-encrypt node-querystring
  node-querystring-es3 node-randombytes node-randomfill node-readdirp
  node-repeat-string node-require-directory node-resolve-cwd node-resolve-dir
  node-resolve-from node-ripemd160 node-schema-utils node-set-immediate-shim
  node-setimmediate node-sha.js node-source-list-map node-stream-browserify
  node-stream-http node-tapable node-terser node-timers-browserify
  node-to-arraybuffer node-to-regex-range node-tty-browserify node-uri-js
  node-url node-util node-vm-browserify node-watchpack node-webassemblyjs
  node-webpack-sources node-wrap-ansi node-xtend node-y18n node-yargs
  node-yargs-parser
使用'sudo apt autoremove'来卸载它(它们)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 137 个软件包未被升级。
```

**Comment by A4-Tacks** [comment]
你的版本很奇怪，我给一个建议，你将包管理器安装的yarn卸载，使用npm安装yarn…
记得把无用依赖也autoremove掉

**Comment by SquareCM2** [comment]
> 你的版本很奇怪，我给一个建议，你将包管理器安装的yarn卸载，使用npm安装yarn… 记得把无用依赖也autoremove掉

```
$ npm install -g yarn
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/squarecm2/.npm/_logs/2024-04-21T07_12_47_081Z-debug-0.log

```

**Comment by A4-Tacks** [comment]
你是使用root运行的吗？如果不是你应该切换至root或使用sudo将此命令进入root

**Comment by SquareCM2** [comment]
```
$ yarn install
yarn install v1.22.22
warning ../package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
error jsdom@22.1.0: The engine "node" is incompatible with this module. Expected version ">=16". Got "12.22.9"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**Comment by A4-Tacks** [comment]
这是什么远古版本，我建议你去nodejs官网下载20版本的nodejs来换掉包管理器装的比较合适。

**Comment by SquareCM2** [comment]
重装后成功build，关闭issue
